@extends('demo.reservation.layout')
@section('title','ネット予約')
@section('content')
<div class="booking-steps"><span class="active">1 入力</span><span>2 確認</span><span>3 完了</span></div>
<div class="booking-title"><p>ONLINE RESERVATION</p><h1>ネット予約</h1><span>順番に選ぶだけで予約できます。</span></div>
@if($errors->any())<div class="booking-errors"><strong>入力内容をご確認ください</strong><ul>@foreach($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif
<form method="post" action="{{ route('demo.reservation.confirm') }}" id="reservation-form" class="booking-grid">@csrf
<div class="booking-main">
<section class="booking-panel"><h2><span>1</span>メニューを選択</h2><div class="choice-grid">@foreach($services as $service)<label class="choice-card"><input type="radio" name="service_id" value="{{ $service->id }}" data-name="{{ $service->name }}" data-price="{{ number_format($service->price) }}円" @checked(old('service_id')==$service->id) required><span><strong>{{ $service->name }}</strong><small>{{ $service->description }}</small><b>{{ number_format($service->price) }}円</b><em>施術{{ $service->duration_minutes }}分＋準備{{ $service->buffer_minutes }}分</em></span></label>@endforeach</div></section>
<section class="booking-panel" id="staff-panel"><h2><span>2</span>スタッフを選択</h2><div id="staff-list" class="choice-grid"><p class="booking-help">先にメニューを選択してください。</p></div></section>
<section class="booking-panel"><h2><span>3</span>日付を選択</h2><input class="booking-input" type="date" name="date" id="booking-date" min="{{ now()->toDateString() }}" max="{{ now()->addMonths(3)->toDateString() }}" value="{{ old('date',now()->addDay()->toDateString()) }}" required></section>
<section class="booking-panel"><h2><span>4</span>空いている時間を選択</h2><div id="slot-list" class="slot-grid"><p class="booking-help">メニュー・スタッフ・日付を選択すると表示されます。</p></div><input type="hidden" name="starts_at" id="starts-at" value="{{ old('starts_at') }}"></section>
<section class="booking-panel"><h2><span>5</span>お客さま情報</h2><div class="field-grid"><label>お名前<span>必須</span><input class="booking-input" name="customer_name" value="{{ old('customer_name') }}" autocomplete="name" required></label><label>電話番号<span>必須</span><input class="booking-input" name="phone" value="{{ old('phone') }}" inputmode="tel" autocomplete="tel" required></label><label>メールアドレス<span>必須</span><input class="booking-input" type="email" name="email" value="{{ old('email') }}" autocomplete="email" required></label><label>備考<textarea class="booking-input" name="notes" rows="4">{{ old('notes') }}</textarea></label></div></section>
</div>
<aside class="booking-summary"><h2>選択内容</h2><dl><div><dt>メニュー</dt><dd id="summary-service">未選択</dd></div><div><dt>スタッフ</dt><dd id="summary-staff">未選択</dd></div><div><dt>日時</dt><dd id="summary-date">未選択</dd></div><div><dt>料金</dt><dd id="summary-price">—</dd></div></dl><button class="booking-primary" type="submit">入力内容を確認する <span>→</span></button><small>まだ予約は確定しません</small></aside>
</form>
@endsection
@push('scripts')<script>
const form=document.querySelector('#reservation-form'),staffList=document.querySelector('#staff-list'),slotList=document.querySelector('#slot-list'),dateInput=document.querySelector('#booking-date'),startInput=document.querySelector('#starts-at');
const selected=(n)=>document.querySelector(`input[name="${n}"]:checked`);
const escapeHtml=(value)=>String(value??'').replace(/[&<>"']/g,(char)=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[char]));
function summary(){const s=selected('service_id'),st=selected('staff_id'),sl=selected('slot');document.querySelector('#summary-service').textContent=s?.dataset.name||'未選択';document.querySelector('#summary-price').textContent=s?.dataset.price||'—';document.querySelector('#summary-staff').textContent=st?.dataset.name||'未選択';document.querySelector('#summary-date').textContent=sl?`${dateInput.value} ${sl.dataset.label}`:'未選択';}
async function loadStaffs(){const service=selected('service_id');if(!service)return;staffList.innerHTML='<p class="booking-help">読み込み中...</p>';const data=await fetch(`/demo/reservation/staffs/${service.value}`).then(r=>r.json());staffList.innerHTML=data.map(x=>`<label class="choice-card"><input type="radio" name="staff_id" value="${Number(x.id)}" data-name="${escapeHtml(x.name)}" required><span><strong>${escapeHtml(x.name)}</strong><small>${escapeHtml(x.bio)}</small><b>指名料 ${Number(x.nomination_fee).toLocaleString()}円</b></span></label>`).join('');if(data.length===1){staffList.querySelector('input').checked=true;}staffList.querySelectorAll('input').forEach(x=>x.addEventListener('change',()=>{loadSlots();summary()}));summary();loadSlots();}
async function loadSlots(){const service=selected('service_id'),staff=selected('staff_id');startInput.value='';if(!service||!staff||!dateInput.value){slotList.innerHTML='<p class="booking-help">必要な項目を選択してください。</p>';return;}slotList.innerHTML='<p class="booking-help">空き時間を確認中...</p>';const q=new URLSearchParams({service_id:service.value,staff_id:staff.value,date:dateInput.value});const res=await fetch(`/demo/reservation/slots?${q}`);const data=res.ok?await res.json():[];slotList.innerHTML=data.length?data.map(x=>`<label class="slot"><input type="radio" name="slot" value="${x.value}" data-label="${x.label}"><span>${x.label}</span></label>`).join(''):'<p class="booking-help">この日は空きがありません。</p>';slotList.querySelectorAll('input').forEach(x=>x.addEventListener('change',()=>{startInput.value=x.value;summary()}));summary();}
document.querySelectorAll('input[name="service_id"]').forEach(x=>x.addEventListener('change',()=>{loadStaffs();summary()}));dateInput.addEventListener('change',loadSlots);if(selected('service_id'))loadStaffs();summary();
form.addEventListener('submit',e=>{if(!startInput.value){e.preventDefault();alert('予約時間を選択してください。');}});
</script>@endpush
